### ISSUE TITLE
Current undocumented requirements to use the railtie.

### ISSUE THREAD

**Issue by undergroundwebdesigns** [apotonick/tyrant#1]
- Requires warden `gem "warden"` in your gemfile, separately from Tyrant.
- Requires using the master version of the gem from Github. `gem 'tyrant', github: "apotonick/tyrant", branch: "master"`.

Without those you may get a strange `bin/rails:6: warning: already initialized constant APP_PATH` error on startup.

**Comment by apotonick** [comment]
Whoohoo, issue no. 1! Yeah, I will clean this up once I feel Tyrant is ready for a first release. Thanks!
